(() => {
'use strict';const $=id=>document.getElementById(id),c=$('fieldCanvas'),L=Lab;let charges=[],drag=null,probes=[],clock=0;
const heat=L.toggle('potential','Potential overlay',false),probe=L.toggle('probe','Release positive probe on click',false);
L.note('Drag charges to reshape the field. Probe mode: click empty space to release a positive test charge. Red = positive potential; blue = negative. Field arrows point from + to −. Qualitative motion, arbitrary units.');
function field(px,py){let ex=0,ey=0,pot=0;charges.forEach(q=>{const dx=px-q.x,dy=py-q.y,r2=Math.max(dx*dx+dy*dy,180),r=Math.sqrt(r2);ex+=q.q*dx/(r2*r);ey+=q.q*dy/(r2*r);pot+=q.q/r;});return{ex,ey,pot};}
function draw(){const x=L.fit(c);if(!x)return;const w=c.clientWidth,h=c.clientHeight;L.scene(x,w,h,'ELECTROSTATICS / FIELD MAPPER');
if(heat.checked)for(let py=40;py<h;py+=18)for(let px=0;px<w;px+=18){const e=field(px,py);x.fillStyle=(e.pot>0?'rgba(251,113,133,':'rgba(96,165,250,')+Math.min(.5,Math.abs(e.pot)*4)+')';x.fillRect(px,py,18,18);}
if($('showVectors').checked)for(let py=55;py<h;py+=38)for(let px=25;px<w;px+=38){const e=field(px,py),n=Math.hypot(e.ex,e.ey);if(n>1e-8){const m=Math.min(18,7+n*1500);L.arrow(x,px,py,px+e.ex/n*m,py+e.ey/n*m,'#8aa9c077');}}
if($('showLines').checked)charges.forEach(q=>{for(let a=0;a<Math.PI*2;a+=Math.PI/6){let px=q.x+Math.cos(a)*19,py=q.y+Math.sin(a)*19;const points=[];for(let i=0;i<160;i++){points.push([px,py]);const e=field(px,py),n=Math.hypot(e.ex,e.ey);if(n<1e-9)break;px+=e.ex/n*4*Math.sign(q.q);py+=e.ey/n*4*Math.sign(q.q);if(px<0||px>w||py<38||py>h||charges.some(r=>r!==q&&Math.hypot(px-r.x,py-r.y)<17))break;}x.save();x.strokeStyle=q.q>0?'#fb718588':'#60a5fa88';x.beginPath();points.forEach((p,i)=>i?x.lineTo(...p):x.moveTo(...p));x.stroke();x.restore();if(points.length>10){const j=Math.floor((clock*18)%points.length),p=points[q.q>0?j:points.length-1-j];L.ball(x,p[0],p[1],2.5,'#e2e8f0');}}});
probes.forEach(p=>{for(let i=1;i<p.trail.length;i++)L.line(x,...p.trail[i-1],...p.trail[i],'#fbbf2477');L.ball(x,p.x,p.y,4,'#fbbf24',true);});
charges.forEach(q=>{L.ball(x,q.x,q.y,18,q.q>0?'#fb7185':'#60a5fa',true);x.save();x.font='bold 21px system-ui';x.textAlign='center';x.fillStyle='#fff';x.fillText(q.q>0?'+':'−',q.x,q.y+7);x.restore();});
$('chargeCountOut').textContent=charges.length;$('positiveOut').textContent=charges.filter(q=>q.q>0).length;$('negativeOut').textContent=charges.filter(q=>q.q<0).length;const e=field(w/2,h/2);$('fieldOut').textContent=Math.hypot(e.ex,e.ey).toExponential(2);
}
function add(s){if(charges.length>=16)return;charges.push({x:35+Math.random()*Math.max(1,c.clientWidth-70),y:65+Math.random()*Math.max(1,c.clientHeight-100),q:s*+$('magnitude').value});draw();}
$('addPositive').onclick=()=>add(1);$('addNegative').onclick=()=>add(-1);$('reset').onclick=()=>{charges=[];probes=[];draw();};
document.querySelectorAll('.control-panel input').forEach(e=>e.oninput=()=>{const o=$(e.id+'Value');if(o)o.value=e.value+(e.dataset.unit||'');draw();});
c.onpointerdown=e=>{const r=c.getBoundingClientRect(),px=e.clientX-r.left,py=e.clientY-r.top;drag=charges.find(q=>Math.hypot(q.x-px,q.y-py)<23);c.setPointerCapture(e.pointerId);if(!drag&&probe.checked){probes.push({x:px,y:py,vx:0,vy:0,trail:[],age:0});if(probes.length>8)probes.shift();}};
c.onpointermove=e=>{if(drag){const r=c.getBoundingClientRect();drag.x=Math.max(20,Math.min(c.clientWidth-20,e.clientX-r.left));drag.y=Math.max(45,Math.min(c.clientHeight-20,e.clientY-r.top));draw();}};c.onpointerup=c.onpointercancel=()=>drag=null;
$('checkChallenge').onclick=()=>{const ok=charges.length===2&&charges[0].q*charges[1].q<0,f=$('challengeFeedback');f.textContent=ok?'Dipole created. Field runs from + to −.':'Use exactly one positive and one negative charge.';f.className='challenge__feedback '+(ok?'is-success':'is-error');};
L.animate(dt=>{clock+=L.reduced.matches?0:dt;probes.forEach(p=>{const e=field(p.x,p.y);p.vx+=e.ex*90000*dt;p.vy+=e.ey*90000*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.age+=dt;p.trail.push([p.x,p.y]);if(p.trail.length>60)p.trail.shift();});probes=probes.filter(p=>p.age<15&&p.x>0&&p.x<c.clientWidth&&p.y>35&&p.y<c.clientHeight&&!charges.some(q=>Math.hypot(q.x-p.x,q.y-p.y)<17));if(charges.length||probes.length)draw();});new ResizeObserver(()=>{charges.forEach(q=>{q.x=Math.max(20,Math.min(c.clientWidth-20,q.x));q.y=Math.max(45,Math.min(c.clientHeight-20,q.y));});draw();}).observe(c);draw();
})();
