(() => {
'use strict';const $=id=>document.getElementById(id),c=$('wavesCanvas'),L=Lab;let time=0,paused=L.reduced.matches,target=Math.random()>.5?'constructive':'destructive';
const mode=$('mode');mode.add(new Option('Custom phase','custom'));mode.add(new Option('Standing wave','standing'));
const surface=L.toggle('surfaceView','Surface ripple view',false),pause=document.createElement('button');pause.className='button button--secondary';pause.textContent=paused?'Play waves':'Pause waves';document.querySelector('.control-panel').append(pause);pause.onclick=()=>{paused=!paused;pause.textContent=paused?'Play waves':'Pause waves';};
L.note('Blue: Wave 1 · Green: Wave 2 · Violet: sum. Standing waves have fixed nodes (zero displacement) and antinodes (maximum amplitude). Surface view shows two circular sources. Speed, frequency and wavelength stay linked by v = fλ.');
const v=id=>+$(id).value;
function draw(){const x=L.fit(c);if(!x)return;const w=c.clientWidth,h=c.clientHeight,A=v('amplitude'),lam=v('wavelength'),m=mode.value,extra=(m==='constructive'||m==='standing')?0:m==='destructive'?Math.PI:v('phase')*Math.PI/180,phase=2*Math.PI*v('frequency')*time;
L.scene(x,w,h,surface.checked?'RIPPLE TANK / PERSPECTIVE':'SUPERPOSITION / OSCILLOSCOPE');
if(surface.checked){for(let row=0;row<32;row++){x.beginPath();for(let col=0;col<=70;col++){const u=(col/70-.5)*w,z=row/31,dist1=Math.hypot(u+w*.18,z*250-120),dist2=Math.hypot(u-w*.18,z*250-120),a=Math.sin(dist1*2*Math.PI/lam-phase),b=m==='single'?0:Math.sin(dist2*2*Math.PI/lam-phase+extra),px=w/2+u*(.4+z*.55),py=80+z*(h-140)+(a+b)*A*.18;col?x.lineTo(px,py):x.moveTo(px,py);}x.strokeStyle='hsla('+(170+row*2)+',85%,68%,'+(.3+row/50)+')';x.stroke();}L.label(x,'Two-source surface model · crest / trough mesh',18,h-20);}
else {const ys=[h*.23,h*.51,h*.8],colors=['#60a5fa','#34d399','#c084fc'];for(let k=0;k<3;k++){L.line(x,10,ys[k],w-10,ys[k],'#ffffff18');L.label(x,['01 / WAVE 1','02 / WAVE 2','03 / RESULTANT'][k],16,ys[k]-h*.10,colors[k]);x.save();x.strokeStyle=colors[k];x.lineWidth=k===2?3:2;x.shadowColor=colors[k];x.shadowBlur=8;x.beginPath();for(let px=0;px<w;px+=2){const a=A*Math.sin(2*Math.PI*px/lam-phase),b=m==='single'?0:A*Math.sin(2*Math.PI*px/lam+(m==='standing'?phase:-phase)+extra),y=ys[k]-(k===0?a:k===1?b:a+b)*Math.min(.5,h/650);px?x.lineTo(px,y):x.moveTo(px,y);}x.stroke();x.restore();}
if(m==='standing'){for(let px=0;px<w;px+=lam/2){L.ball(x,px,ys[2],4,'#fbbf24');L.label(x,'N',px+5,ys[2]+18,'#fbbf24');if(px+lam/4<w)L.label(x,'A',px+lam/4,ys[2]+22,'#c084fc');}}}
$('amplitudeOut').textContent=A+' px';$('frequencyOut').textContent=v('frequency').toFixed(2)+' Hz';$('wavelengthOut').textContent=lam+' px';$('phaseOut').textContent=(extra*180/Math.PI).toFixed(0)+'°';$('speedOut').textContent=(v('frequency')*lam).toFixed(0)+' px/s';$('calculatedSpeedOut').textContent=(v('frequency')*lam).toFixed(0)+' px/s';
}
function labels(){document.querySelectorAll('input[type=range]').forEach(e=>{$(e.id+'Value').value=e.value+(e.dataset.unit||'');});}
document.querySelectorAll('input[type=range]').forEach(e=>e.oninput=()=>{if(e.id==='phase')mode.value='custom';if(e.id==='speed')$('frequency').value=v('speed')/v('wavelength');else $('speed').value=v('frequency')*v('wavelength');labels();draw();});
$('frequency').min='.01';$('frequency').max='6';$('frequency').step='.001';$('speed').max='1440';$('speed').min='.5';$('speed').step='.01';mode.onchange=draw;surface.onchange=draw;
$('reset').onclick=()=>{document.querySelectorAll('input[type=range]').forEach(e=>e.value=e.defaultValue);mode.value='single';surface.checked=false;time=0;labels();draw();};
$('waveTarget').textContent='Target: '+target;$('checkChallenge').onclick=()=>{const p=v('phase')%360,ok=mode.value===target||(mode.value==='custom'&&(target==='constructive'?p===0:p===180)),f=$('challengeFeedback');f.textContent=ok?'Pattern achieved.':'Select or create '+target+' interference.';f.className='challenge__feedback '+(ok?'is-success':'is-error');};
L.animate(dt=>{if(!paused){time+=dt;draw();}});new ResizeObserver(draw).observe(c);draw();
})();
