/* Offline public element data: PubChem periodic table, retrieved 2026-09-08.
 * https://pubchem.ncbi.nlm.nih.gov/rest/pug/periodictable/JSON
 * Lr configuration corrected using https://physics.nist.gov/cgi-bin/Elements/elInfo.pl?element=103
 * Source mass values are retained; radioactive-element values may represent an isotope.
 */
window.PeriodicElements = [
  {
    "number": 1,
    "symbol": "H",
    "name": "Hydrogen",
    "period": 1,
    "group": 1,
    "row": 2,
    "column": 1,
    "mass": "1.0080",
    "category": "nonmetal",
    "config": "1s1",
    "shells": [
      1
    ],
    "electronegativity": "2.2",
    "configSource": "PubChem"
  },
  {
    "number": 2,
    "symbol": "He",
    "name": "Helium",
    "period": 1,
    "group": 18,
    "row": 2,
    "column": 18,
    "mass": "4.00260",
    "category": "noble gas",
    "config": "1s2",
    "shells": [
      2
    ],
    "electronegativity": null,
    "configSource": "PubChem"
  },
  {
    "number": 3,
    "symbol": "Li",
    "name": "Lithium",
    "period": 2,
    "group": 1,
    "row": 3,
    "column": 1,
    "mass": "7.0",
    "category": "alkali metal",
    "config": "[He]2s1",
    "shells": [
      2,
      1
    ],
    "electronegativity": "0.98",
    "configSource": "PubChem"
  },
  {
    "number": 4,
    "symbol": "Be",
    "name": "Beryllium",
    "period": 2,
    "group": 2,
    "row": 3,
    "column": 2,
    "mass": "9.012183",
    "category": "alkaline earth metal",
    "config": "[He]2s2",
    "shells": [
      2,
      2
    ],
    "electronegativity": "1.57",
    "configSource": "PubChem"
  },
  {
    "number": 5,
    "symbol": "B",
    "name": "Boron",
    "period": 2,
    "group": 13,
    "row": 3,
    "column": 13,
    "mass": "10.81",
    "category": "metalloid",
    "config": "[He]2s2 2p1",
    "shells": [
      2,
      3
    ],
    "electronegativity": "2.04",
    "configSource": "PubChem"
  },
  {
    "number": 6,
    "symbol": "C",
    "name": "Carbon",
    "period": 2,
    "group": 14,
    "row": 3,
    "column": 14,
    "mass": "12.011",
    "category": "nonmetal",
    "config": "[He]2s2 2p2",
    "shells": [
      2,
      4
    ],
    "electronegativity": "2.55",
    "configSource": "PubChem"
  },
  {
    "number": 7,
    "symbol": "N",
    "name": "Nitrogen",
    "period": 2,
    "group": 15,
    "row": 3,
    "column": 15,
    "mass": "14.007",
    "category": "nonmetal",
    "config": "[He] 2s2 2p3",
    "shells": [
      2,
      5
    ],
    "electronegativity": "3.04",
    "configSource": "PubChem"
  },
  {
    "number": 8,
    "symbol": "O",
    "name": "Oxygen",
    "period": 2,
    "group": 16,
    "row": 3,
    "column": 16,
    "mass": "15.999",
    "category": "nonmetal",
    "config": "[He]2s2 2p4",
    "shells": [
      2,
      6
    ],
    "electronegativity": "3.44",
    "configSource": "PubChem"
  },
  {
    "number": 9,
    "symbol": "F",
    "name": "Fluorine",
    "period": 2,
    "group": 17,
    "row": 3,
    "column": 17,
    "mass": "18.99840316",
    "category": "halogen",
    "config": "[He]2s2 2p5",
    "shells": [
      2,
      7
    ],
    "electronegativity": "3.98",
    "configSource": "PubChem"
  },
  {
    "number": 10,
    "symbol": "Ne",
    "name": "Neon",
    "period": 2,
    "group": 18,
    "row": 3,
    "column": 18,
    "mass": "20.180",
    "category": "noble gas",
    "config": "[He]2s2 2p6",
    "shells": [
      2,
      8
    ],
    "electronegativity": null,
    "configSource": "PubChem"
  },
  {
    "number": 11,
    "symbol": "Na",
    "name": "Sodium",
    "period": 3,
    "group": 1,
    "row": 4,
    "column": 1,
    "mass": "22.9897693",
    "category": "alkali metal",
    "config": "[Ne]3s1",
    "shells": [
      2,
      8,
      1
    ],
    "electronegativity": "0.93",
    "configSource": "PubChem"
  },
  {
    "number": 12,
    "symbol": "Mg",
    "name": "Magnesium",
    "period": 3,
    "group": 2,
    "row": 4,
    "column": 2,
    "mass": "24.305",
    "category": "alkaline earth metal",
    "config": "[Ne]3s2",
    "shells": [
      2,
      8,
      2
    ],
    "electronegativity": "1.31",
    "configSource": "PubChem"
  },
  {
    "number": 13,
    "symbol": "Al",
    "name": "Aluminum",
    "period": 3,
    "group": 13,
    "row": 4,
    "column": 13,
    "mass": "26.981538",
    "category": "post-transition metal",
    "config": "[Ne]3s2 3p1",
    "shells": [
      2,
      8,
      3
    ],
    "electronegativity": "1.61",
    "configSource": "PubChem"
  },
  {
    "number": 14,
    "symbol": "Si",
    "name": "Silicon",
    "period": 3,
    "group": 14,
    "row": 4,
    "column": 14,
    "mass": "28.085",
    "category": "metalloid",
    "config": "[Ne]3s2 3p2",
    "shells": [
      2,
      8,
      4
    ],
    "electronegativity": "1.9",
    "configSource": "PubChem"
  },
  {
    "number": 15,
    "symbol": "P",
    "name": "Phosphorus",
    "period": 3,
    "group": 15,
    "row": 4,
    "column": 15,
    "mass": "30.97376200",
    "category": "nonmetal",
    "config": "[Ne]3s2 3p3",
    "shells": [
      2,
      8,
      5
    ],
    "electronegativity": "2.19",
    "configSource": "PubChem"
  },
  {
    "number": 16,
    "symbol": "S",
    "name": "Sulfur",
    "period": 3,
    "group": 16,
    "row": 4,
    "column": 16,
    "mass": "32.07",
    "category": "nonmetal",
    "config": "[Ne]3s2 3p4",
    "shells": [
      2,
      8,
      6
    ],
    "electronegativity": "2.58",
    "configSource": "PubChem"
  },
  {
    "number": 17,
    "symbol": "Cl",
    "name": "Chlorine",
    "period": 3,
    "group": 17,
    "row": 4,
    "column": 17,
    "mass": "35.45",
    "category": "halogen",
    "config": "[Ne]3s2 3p5",
    "shells": [
      2,
      8,
      7
    ],
    "electronegativity": "3.16",
    "configSource": "PubChem"
  },
  {
    "number": 18,
    "symbol": "Ar",
    "name": "Argon",
    "period": 3,
    "group": 18,
    "row": 4,
    "column": 18,
    "mass": "39.9",
    "category": "noble gas",
    "config": "[Ne]3s2 3p6",
    "shells": [
      2,
      8,
      8
    ],
    "electronegativity": null,
    "configSource": "PubChem"
  },
  {
    "number": 19,
    "symbol": "K",
    "name": "Potassium",
    "period": 4,
    "group": 1,
    "row": 5,
    "column": 1,
    "mass": "39.0983",
    "category": "alkali metal",
    "config": "[Ar]4s1",
    "shells": [
      2,
      8,
      8,
      1
    ],
    "electronegativity": "0.82",
    "configSource": "PubChem"
  },
  {
    "number": 20,
    "symbol": "Ca",
    "name": "Calcium",
    "period": 4,
    "group": 2,
    "row": 5,
    "column": 2,
    "mass": "40.08",
    "category": "alkaline earth metal",
    "config": "[Ar]4s2",
    "shells": [
      2,
      8,
      8,
      2
    ],
    "electronegativity": "1",
    "configSource": "PubChem"
  },
  {
    "number": 21,
    "symbol": "Sc",
    "name": "Scandium",
    "period": 4,
    "group": 3,
    "row": 5,
    "column": 3,
    "mass": "44.95591",
    "category": "transition metal",
    "config": "[Ar]4s2 3d1",
    "shells": [
      2,
      8,
      9,
      2
    ],
    "electronegativity": "1.36",
    "configSource": "PubChem"
  },
  {
    "number": 22,
    "symbol": "Ti",
    "name": "Titanium",
    "period": 4,
    "group": 4,
    "row": 5,
    "column": 4,
    "mass": "47.867",
    "category": "transition metal",
    "config": "[Ar]4s2 3d2",
    "shells": [
      2,
      8,
      10,
      2
    ],
    "electronegativity": "1.54",
    "configSource": "PubChem"
  },
  {
    "number": 23,
    "symbol": "V",
    "name": "Vanadium",
    "period": 4,
    "group": 5,
    "row": 5,
    "column": 5,
    "mass": "50.9415",
    "category": "transition metal",
    "config": "[Ar]4s2 3d3",
    "shells": [
      2,
      8,
      11,
      2
    ],
    "electronegativity": "1.63",
    "configSource": "PubChem"
  },
  {
    "number": 24,
    "symbol": "Cr",
    "name": "Chromium",
    "period": 4,
    "group": 6,
    "row": 5,
    "column": 6,
    "mass": "51.996",
    "category": "transition metal",
    "config": "[Ar]3d5 4s1",
    "shells": [
      2,
      8,
      13,
      1
    ],
    "electronegativity": "1.66",
    "configSource": "PubChem"
  },
  {
    "number": 25,
    "symbol": "Mn",
    "name": "Manganese",
    "period": 4,
    "group": 7,
    "row": 5,
    "column": 7,
    "mass": "54.93804",
    "category": "transition metal",
    "config": "[Ar]4s2 3d5",
    "shells": [
      2,
      8,
      13,
      2
    ],
    "electronegativity": "1.55",
    "configSource": "PubChem"
  },
  {
    "number": 26,
    "symbol": "Fe",
    "name": "Iron",
    "period": 4,
    "group": 8,
    "row": 5,
    "column": 8,
    "mass": "55.84",
    "category": "transition metal",
    "config": "[Ar]4s2 3d6",
    "shells": [
      2,
      8,
      14,
      2
    ],
    "electronegativity": "1.83",
    "configSource": "PubChem"
  },
  {
    "number": 27,
    "symbol": "Co",
    "name": "Cobalt",
    "period": 4,
    "group": 9,
    "row": 5,
    "column": 9,
    "mass": "58.93319",
    "category": "transition metal",
    "config": "[Ar]4s2 3d7",
    "shells": [
      2,
      8,
      15,
      2
    ],
    "electronegativity": "1.88",
    "configSource": "PubChem"
  },
  {
    "number": 28,
    "symbol": "Ni",
    "name": "Nickel",
    "period": 4,
    "group": 10,
    "row": 5,
    "column": 10,
    "mass": "58.693",
    "category": "transition metal",
    "config": "[Ar]4s2 3d8",
    "shells": [
      2,
      8,
      16,
      2
    ],
    "electronegativity": "1.91",
    "configSource": "PubChem"
  },
  {
    "number": 29,
    "symbol": "Cu",
    "name": "Copper",
    "period": 4,
    "group": 11,
    "row": 5,
    "column": 11,
    "mass": "63.55",
    "category": "transition metal",
    "config": "[Ar]4s1 3d10",
    "shells": [
      2,
      8,
      18,
      1
    ],
    "electronegativity": "1.9",
    "configSource": "PubChem"
  },
  {
    "number": 30,
    "symbol": "Zn",
    "name": "Zinc",
    "period": 4,
    "group": 12,
    "row": 5,
    "column": 12,
    "mass": "65.4",
    "category": "transition metal",
    "config": "[Ar]4s2 3d10",
    "shells": [
      2,
      8,
      18,
      2
    ],
    "electronegativity": "1.65",
    "configSource": "PubChem"
  },
  {
    "number": 31,
    "symbol": "Ga",
    "name": "Gallium",
    "period": 4,
    "group": 13,
    "row": 5,
    "column": 13,
    "mass": "69.723",
    "category": "post-transition metal",
    "config": "[Ar]4s2 3d10 4p1",
    "shells": [
      2,
      8,
      18,
      3
    ],
    "electronegativity": "1.81",
    "configSource": "PubChem"
  },
  {
    "number": 32,
    "symbol": "Ge",
    "name": "Germanium",
    "period": 4,
    "group": 14,
    "row": 5,
    "column": 14,
    "mass": "72.63",
    "category": "metalloid",
    "config": "[Ar]4s2 3d10 4p2",
    "shells": [
      2,
      8,
      18,
      4
    ],
    "electronegativity": "2.01",
    "configSource": "PubChem"
  },
  {
    "number": 33,
    "symbol": "As",
    "name": "Arsenic",
    "period": 4,
    "group": 15,
    "row": 5,
    "column": 15,
    "mass": "74.92159",
    "category": "metalloid",
    "config": "[Ar]4s2 3d10 4p3",
    "shells": [
      2,
      8,
      18,
      5
    ],
    "electronegativity": "2.18",
    "configSource": "PubChem"
  },
  {
    "number": 34,
    "symbol": "Se",
    "name": "Selenium",
    "period": 4,
    "group": 16,
    "row": 5,
    "column": 16,
    "mass": "78.97",
    "category": "nonmetal",
    "config": "[Ar]4s2 3d10 4p4",
    "shells": [
      2,
      8,
      18,
      6
    ],
    "electronegativity": "2.55",
    "configSource": "PubChem"
  },
  {
    "number": 35,
    "symbol": "Br",
    "name": "Bromine",
    "period": 4,
    "group": 17,
    "row": 5,
    "column": 17,
    "mass": "79.90",
    "category": "halogen",
    "config": "[Ar]4s2 3d10 4p5",
    "shells": [
      2,
      8,
      18,
      7
    ],
    "electronegativity": "2.96",
    "configSource": "PubChem"
  },
  {
    "number": 36,
    "symbol": "Kr",
    "name": "Krypton",
    "period": 4,
    "group": 18,
    "row": 5,
    "column": 18,
    "mass": "83.80",
    "category": "noble gas",
    "config": "[Ar]4s2 3d10 4p6",
    "shells": [
      2,
      8,
      18,
      8
    ],
    "electronegativity": "3",
    "configSource": "PubChem"
  },
  {
    "number": 37,
    "symbol": "Rb",
    "name": "Rubidium",
    "period": 5,
    "group": 1,
    "row": 6,
    "column": 1,
    "mass": "85.468",
    "category": "alkali metal",
    "config": "[Kr]5s1",
    "shells": [
      2,
      8,
      18,
      8,
      1
    ],
    "electronegativity": "0.82",
    "configSource": "PubChem"
  },
  {
    "number": 38,
    "symbol": "Sr",
    "name": "Strontium",
    "period": 5,
    "group": 2,
    "row": 6,
    "column": 2,
    "mass": "87.62",
    "category": "alkaline earth metal",
    "config": "[Kr]5s2",
    "shells": [
      2,
      8,
      18,
      8,
      2
    ],
    "electronegativity": "0.95",
    "configSource": "PubChem"
  },
  {
    "number": 39,
    "symbol": "Y",
    "name": "Yttrium",
    "period": 5,
    "group": 3,
    "row": 6,
    "column": 3,
    "mass": "88.90584",
    "category": "transition metal",
    "config": "[Kr]5s2 4d1",
    "shells": [
      2,
      8,
      18,
      9,
      2
    ],
    "electronegativity": "1.22",
    "configSource": "PubChem"
  },
  {
    "number": 40,
    "symbol": "Zr",
    "name": "Zirconium",
    "period": 5,
    "group": 4,
    "row": 6,
    "column": 4,
    "mass": "91.22",
    "category": "transition metal",
    "config": "[Kr]5s2 4d2",
    "shells": [
      2,
      8,
      18,
      10,
      2
    ],
    "electronegativity": "1.33",
    "configSource": "PubChem"
  },
  {
    "number": 41,
    "symbol": "Nb",
    "name": "Niobium",
    "period": 5,
    "group": 5,
    "row": 6,
    "column": 5,
    "mass": "92.90637",
    "category": "transition metal",
    "config": "[Kr]5s1 4d4",
    "shells": [
      2,
      8,
      18,
      12,
      1
    ],
    "electronegativity": "1.6",
    "configSource": "PubChem"
  },
  {
    "number": 42,
    "symbol": "Mo",
    "name": "Molybdenum",
    "period": 5,
    "group": 6,
    "row": 6,
    "column": 6,
    "mass": "95.95",
    "category": "transition metal",
    "config": "[Kr]5s1 4d5",
    "shells": [
      2,
      8,
      18,
      13,
      1
    ],
    "electronegativity": "2.16",
    "configSource": "PubChem"
  },
  {
    "number": 43,
    "symbol": "Tc",
    "name": "Technetium",
    "period": 5,
    "group": 7,
    "row": 6,
    "column": 7,
    "mass": "96.90636",
    "category": "transition metal",
    "config": "[Kr]5s2 4d5",
    "shells": [
      2,
      8,
      18,
      13,
      2
    ],
    "electronegativity": "1.9",
    "configSource": "PubChem"
  },
  {
    "number": 44,
    "symbol": "Ru",
    "name": "Ruthenium",
    "period": 5,
    "group": 8,
    "row": 6,
    "column": 8,
    "mass": "101.1",
    "category": "transition metal",
    "config": "[Kr]5s1 4d7",
    "shells": [
      2,
      8,
      18,
      15,
      1
    ],
    "electronegativity": "2.2",
    "configSource": "PubChem"
  },
  {
    "number": 45,
    "symbol": "Rh",
    "name": "Rhodium",
    "period": 5,
    "group": 9,
    "row": 6,
    "column": 9,
    "mass": "102.9055",
    "category": "transition metal",
    "config": "[Kr]5s1 4d8",
    "shells": [
      2,
      8,
      18,
      16,
      1
    ],
    "electronegativity": "2.28",
    "configSource": "PubChem"
  },
  {
    "number": 46,
    "symbol": "Pd",
    "name": "Palladium",
    "period": 5,
    "group": 10,
    "row": 6,
    "column": 10,
    "mass": "106.42",
    "category": "transition metal",
    "config": "[Kr]4d10",
    "shells": [
      2,
      8,
      18,
      18
    ],
    "electronegativity": "2.2",
    "configSource": "PubChem"
  },
  {
    "number": 47,
    "symbol": "Ag",
    "name": "Silver",
    "period": 5,
    "group": 11,
    "row": 6,
    "column": 11,
    "mass": "107.868",
    "category": "transition metal",
    "config": "[Kr]5s1 4d10",
    "shells": [
      2,
      8,
      18,
      18,
      1
    ],
    "electronegativity": "1.93",
    "configSource": "PubChem"
  },
  {
    "number": 48,
    "symbol": "Cd",
    "name": "Cadmium",
    "period": 5,
    "group": 12,
    "row": 6,
    "column": 12,
    "mass": "112.41",
    "category": "transition metal",
    "config": "[Kr]5s2 4d10",
    "shells": [
      2,
      8,
      18,
      18,
      2
    ],
    "electronegativity": "1.69",
    "configSource": "PubChem"
  },
  {
    "number": 49,
    "symbol": "In",
    "name": "Indium",
    "period": 5,
    "group": 13,
    "row": 6,
    "column": 13,
    "mass": "114.818",
    "category": "post-transition metal",
    "config": "[Kr]5s2 4d10 5p1",
    "shells": [
      2,
      8,
      18,
      18,
      3
    ],
    "electronegativity": "1.78",
    "configSource": "PubChem"
  },
  {
    "number": 50,
    "symbol": "Sn",
    "name": "Tin",
    "period": 5,
    "group": 14,
    "row": 6,
    "column": 14,
    "mass": "118.71",
    "category": "post-transition metal",
    "config": "[Kr]5s2 4d10 5p2",
    "shells": [
      2,
      8,
      18,
      18,
      4
    ],
    "electronegativity": "1.96",
    "configSource": "PubChem"
  },
  {
    "number": 51,
    "symbol": "Sb",
    "name": "Antimony",
    "period": 5,
    "group": 15,
    "row": 6,
    "column": 15,
    "mass": "121.760",
    "category": "metalloid",
    "config": "[Kr]5s2 4d10 5p3",
    "shells": [
      2,
      8,
      18,
      18,
      5
    ],
    "electronegativity": "2.05",
    "configSource": "PubChem"
  },
  {
    "number": 52,
    "symbol": "Te",
    "name": "Tellurium",
    "period": 5,
    "group": 16,
    "row": 6,
    "column": 16,
    "mass": "127.6",
    "category": "metalloid",
    "config": "[Kr]5s2 4d10 5p4",
    "shells": [
      2,
      8,
      18,
      18,
      6
    ],
    "electronegativity": "2.1",
    "configSource": "PubChem"
  },
  {
    "number": 53,
    "symbol": "I",
    "name": "Iodine",
    "period": 5,
    "group": 17,
    "row": 6,
    "column": 17,
    "mass": "126.9045",
    "category": "halogen",
    "config": "[Kr]5s2 4d10 5p5",
    "shells": [
      2,
      8,
      18,
      18,
      7
    ],
    "electronegativity": "2.66",
    "configSource": "PubChem"
  },
  {
    "number": 54,
    "symbol": "Xe",
    "name": "Xenon",
    "period": 5,
    "group": 18,
    "row": 6,
    "column": 18,
    "mass": "131.29",
    "category": "noble gas",
    "config": "[Kr]5s2 4d10 5p6",
    "shells": [
      2,
      8,
      18,
      18,
      8
    ],
    "electronegativity": "2.6",
    "configSource": "PubChem"
  },
  {
    "number": 55,
    "symbol": "Cs",
    "name": "Cesium",
    "period": 6,
    "group": 1,
    "row": 7,
    "column": 1,
    "mass": "132.9054520",
    "category": "alkali metal",
    "config": "[Xe]6s1",
    "shells": [
      2,
      8,
      18,
      18,
      8,
      1
    ],
    "electronegativity": "0.79",
    "configSource": "PubChem"
  },
  {
    "number": 56,
    "symbol": "Ba",
    "name": "Barium",
    "period": 6,
    "group": 2,
    "row": 7,
    "column": 2,
    "mass": "137.33",
    "category": "alkaline earth metal",
    "config": "[Xe]6s2",
    "shells": [
      2,
      8,
      18,
      18,
      8,
      2
    ],
    "electronegativity": "0.89",
    "configSource": "PubChem"
  },
  {
    "number": 57,
    "symbol": "La",
    "name": "Lanthanum",
    "period": 6,
    "group": null,
    "row": 10,
    "column": 3,
    "mass": "138.9055",
    "category": "lanthanide",
    "config": "[Xe]6s2 5d1",
    "shells": [
      2,
      8,
      18,
      18,
      9,
      2
    ],
    "electronegativity": "1.1",
    "configSource": "PubChem"
  },
  {
    "number": 58,
    "symbol": "Ce",
    "name": "Cerium",
    "period": 6,
    "group": null,
    "row": 10,
    "column": 4,
    "mass": "140.116",
    "category": "lanthanide",
    "config": "[Xe]6s2 4f1 5d1",
    "shells": [
      2,
      8,
      18,
      19,
      9,
      2
    ],
    "electronegativity": "1.12",
    "configSource": "PubChem"
  },
  {
    "number": 59,
    "symbol": "Pr",
    "name": "Praseodymium",
    "period": 6,
    "group": null,
    "row": 10,
    "column": 5,
    "mass": "140.90766",
    "category": "lanthanide",
    "config": "[Xe]6s2 4f3",
    "shells": [
      2,
      8,
      18,
      21,
      8,
      2
    ],
    "electronegativity": "1.13",
    "configSource": "PubChem"
  },
  {
    "number": 60,
    "symbol": "Nd",
    "name": "Neodymium",
    "period": 6,
    "group": null,
    "row": 10,
    "column": 6,
    "mass": "144.24",
    "category": "lanthanide",
    "config": "[Xe]6s2 4f4",
    "shells": [
      2,
      8,
      18,
      22,
      8,
      2
    ],
    "electronegativity": "1.14",
    "configSource": "PubChem"
  },
  {
    "number": 61,
    "symbol": "Pm",
    "name": "Promethium",
    "period": 6,
    "group": null,
    "row": 10,
    "column": 7,
    "mass": "144.91276",
    "category": "lanthanide",
    "config": "[Xe]6s2 4f5",
    "shells": [
      2,
      8,
      18,
      23,
      8,
      2
    ],
    "electronegativity": null,
    "configSource": "PubChem"
  },
  {
    "number": 62,
    "symbol": "Sm",
    "name": "Samarium",
    "period": 6,
    "group": null,
    "row": 10,
    "column": 8,
    "mass": "150.4",
    "category": "lanthanide",
    "config": "[Xe]6s2 4f6",
    "shells": [
      2,
      8,
      18,
      24,
      8,
      2
    ],
    "electronegativity": "1.17",
    "configSource": "PubChem"
  },
  {
    "number": 63,
    "symbol": "Eu",
    "name": "Europium",
    "period": 6,
    "group": null,
    "row": 10,
    "column": 9,
    "mass": "151.964",
    "category": "lanthanide",
    "config": "[Xe]6s2 4f7",
    "shells": [
      2,
      8,
      18,
      25,
      8,
      2
    ],
    "electronegativity": null,
    "configSource": "PubChem"
  },
  {
    "number": 64,
    "symbol": "Gd",
    "name": "Gadolinium",
    "period": 6,
    "group": null,
    "row": 10,
    "column": 10,
    "mass": "157.25",
    "category": "lanthanide",
    "config": "[Xe]6s2 4f7 5d1",
    "shells": [
      2,
      8,
      18,
      25,
      9,
      2
    ],
    "electronegativity": "1.2",
    "configSource": "PubChem"
  },
  {
    "number": 65,
    "symbol": "Tb",
    "name": "Terbium",
    "period": 6,
    "group": null,
    "row": 10,
    "column": 11,
    "mass": "158.92535",
    "category": "lanthanide",
    "config": "[Xe]6s2 4f9",
    "shells": [
      2,
      8,
      18,
      27,
      8,
      2
    ],
    "electronegativity": null,
    "configSource": "PubChem"
  },
  {
    "number": 66,
    "symbol": "Dy",
    "name": "Dysprosium",
    "period": 6,
    "group": null,
    "row": 10,
    "column": 12,
    "mass": "162.500",
    "category": "lanthanide",
    "config": "[Xe]6s2 4f10",
    "shells": [
      2,
      8,
      18,
      28,
      8,
      2
    ],
    "electronegativity": "1.22",
    "configSource": "PubChem"
  },
  {
    "number": 67,
    "symbol": "Ho",
    "name": "Holmium",
    "period": 6,
    "group": null,
    "row": 10,
    "column": 13,
    "mass": "164.93033",
    "category": "lanthanide",
    "config": "[Xe]6s2 4f11",
    "shells": [
      2,
      8,
      18,
      29,
      8,
      2
    ],
    "electronegativity": "1.23",
    "configSource": "PubChem"
  },
  {
    "number": 68,
    "symbol": "Er",
    "name": "Erbium",
    "period": 6,
    "group": null,
    "row": 10,
    "column": 14,
    "mass": "167.26",
    "category": "lanthanide",
    "config": "[Xe]6s2 4f12",
    "shells": [
      2,
      8,
      18,
      30,
      8,
      2
    ],
    "electronegativity": "1.24",
    "configSource": "PubChem"
  },
  {
    "number": 69,
    "symbol": "Tm",
    "name": "Thulium",
    "period": 6,
    "group": null,
    "row": 10,
    "column": 15,
    "mass": "168.93422",
    "category": "lanthanide",
    "config": "[Xe]6s2 4f13",
    "shells": [
      2,
      8,
      18,
      31,
      8,
      2
    ],
    "electronegativity": "1.25",
    "configSource": "PubChem"
  },
  {
    "number": 70,
    "symbol": "Yb",
    "name": "Ytterbium",
    "period": 6,
    "group": null,
    "row": 10,
    "column": 16,
    "mass": "173.05",
    "category": "lanthanide",
    "config": "[Xe]6s2 4f14",
    "shells": [
      2,
      8,
      18,
      32,
      8,
      2
    ],
    "electronegativity": null,
    "configSource": "PubChem"
  },
  {
    "number": 71,
    "symbol": "Lu",
    "name": "Lutetium",
    "period": 6,
    "group": null,
    "row": 10,
    "column": 17,
    "mass": "174.9667",
    "category": "lanthanide",
    "config": "[Xe]6s2 4f14 5d1",
    "shells": [
      2,
      8,
      18,
      32,
      9,
      2
    ],
    "electronegativity": "1.27",
    "configSource": "PubChem"
  },
  {
    "number": 72,
    "symbol": "Hf",
    "name": "Hafnium",
    "period": 6,
    "group": 4,
    "row": 7,
    "column": 4,
    "mass": "178.49",
    "category": "transition metal",
    "config": "[Xe]6s2 4f14 5d2",
    "shells": [
      2,
      8,
      18,
      32,
      10,
      2
    ],
    "electronegativity": "1.3",
    "configSource": "PubChem"
  },
  {
    "number": 73,
    "symbol": "Ta",
    "name": "Tantalum",
    "period": 6,
    "group": 5,
    "row": 7,
    "column": 5,
    "mass": "180.9479",
    "category": "transition metal",
    "config": "[Xe]6s2 4f14 5d3",
    "shells": [
      2,
      8,
      18,
      32,
      11,
      2
    ],
    "electronegativity": "1.5",
    "configSource": "PubChem"
  },
  {
    "number": 74,
    "symbol": "W",
    "name": "Tungsten",
    "period": 6,
    "group": 6,
    "row": 7,
    "column": 6,
    "mass": "183.84",
    "category": "transition metal",
    "config": "[Xe]6s2 4f14 5d4",
    "shells": [
      2,
      8,
      18,
      32,
      12,
      2
    ],
    "electronegativity": "2.36",
    "configSource": "PubChem"
  },
  {
    "number": 75,
    "symbol": "Re",
    "name": "Rhenium",
    "period": 6,
    "group": 7,
    "row": 7,
    "column": 7,
    "mass": "186.207",
    "category": "transition metal",
    "config": "[Xe]6s2 4f14 5d5",
    "shells": [
      2,
      8,
      18,
      32,
      13,
      2
    ],
    "electronegativity": "1.9",
    "configSource": "PubChem"
  },
  {
    "number": 76,
    "symbol": "Os",
    "name": "Osmium",
    "period": 6,
    "group": 8,
    "row": 7,
    "column": 8,
    "mass": "190.2",
    "category": "transition metal",
    "config": "[Xe]6s2 4f14 5d6",
    "shells": [
      2,
      8,
      18,
      32,
      14,
      2
    ],
    "electronegativity": "2.2",
    "configSource": "PubChem"
  },
  {
    "number": 77,
    "symbol": "Ir",
    "name": "Iridium",
    "period": 6,
    "group": 9,
    "row": 7,
    "column": 9,
    "mass": "192.22",
    "category": "transition metal",
    "config": "[Xe]6s2 4f14 5d7",
    "shells": [
      2,
      8,
      18,
      32,
      15,
      2
    ],
    "electronegativity": "2.2",
    "configSource": "PubChem"
  },
  {
    "number": 78,
    "symbol": "Pt",
    "name": "Platinum",
    "period": 6,
    "group": 10,
    "row": 7,
    "column": 10,
    "mass": "195.08",
    "category": "transition metal",
    "config": "[Xe]6s1 4f14 5d9",
    "shells": [
      2,
      8,
      18,
      32,
      17,
      1
    ],
    "electronegativity": "2.28",
    "configSource": "PubChem"
  },
  {
    "number": 79,
    "symbol": "Au",
    "name": "Gold",
    "period": 6,
    "group": 11,
    "row": 7,
    "column": 11,
    "mass": "196.96657",
    "category": "transition metal",
    "config": "[Xe]6s1 4f14 5d10",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      1
    ],
    "electronegativity": "2.54",
    "configSource": "PubChem"
  },
  {
    "number": 80,
    "symbol": "Hg",
    "name": "Mercury",
    "period": 6,
    "group": 12,
    "row": 7,
    "column": 12,
    "mass": "200.59",
    "category": "transition metal",
    "config": "[Xe]6s2 4f14 5d10",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      2
    ],
    "electronegativity": "2",
    "configSource": "PubChem"
  },
  {
    "number": 81,
    "symbol": "Tl",
    "name": "Thallium",
    "period": 6,
    "group": 13,
    "row": 7,
    "column": 13,
    "mass": "204.383",
    "category": "post-transition metal",
    "config": "[Xe]6s2 4f14 5d10 6p1",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      3
    ],
    "electronegativity": "1.62",
    "configSource": "PubChem"
  },
  {
    "number": 82,
    "symbol": "Pb",
    "name": "Lead",
    "period": 6,
    "group": 14,
    "row": 7,
    "column": 14,
    "mass": "207",
    "category": "post-transition metal",
    "config": "[Xe]6s2 4f14 5d10 6p2",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      4
    ],
    "electronegativity": "2.33",
    "configSource": "PubChem"
  },
  {
    "number": 83,
    "symbol": "Bi",
    "name": "Bismuth",
    "period": 6,
    "group": 15,
    "row": 7,
    "column": 15,
    "mass": "208.98040",
    "category": "post-transition metal",
    "config": "[Xe]6s2 4f14 5d10 6p3",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      5
    ],
    "electronegativity": "2.02",
    "configSource": "PubChem"
  },
  {
    "number": 84,
    "symbol": "Po",
    "name": "Polonium",
    "period": 6,
    "group": 16,
    "row": 7,
    "column": 16,
    "mass": "208.98243",
    "category": "metalloid",
    "config": "[Xe]6s2 4f14 5d10 6p4",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      6
    ],
    "electronegativity": "2",
    "configSource": "PubChem"
  },
  {
    "number": 85,
    "symbol": "At",
    "name": "Astatine",
    "period": 6,
    "group": 17,
    "row": 7,
    "column": 17,
    "mass": "209.98715",
    "category": "halogen",
    "config": "[Xe]6s2 4f14 5d10 6p5",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      7
    ],
    "electronegativity": "2.2",
    "configSource": "PubChem"
  },
  {
    "number": 86,
    "symbol": "Rn",
    "name": "Radon",
    "period": 6,
    "group": 18,
    "row": 7,
    "column": 18,
    "mass": "222.01758",
    "category": "noble gas",
    "config": "[Xe]6s2 4f14 5d10 6p6",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      8
    ],
    "electronegativity": null,
    "configSource": "PubChem"
  },
  {
    "number": 87,
    "symbol": "Fr",
    "name": "Francium",
    "period": 7,
    "group": 1,
    "row": 8,
    "column": 1,
    "mass": "223.01973",
    "category": "alkali metal",
    "config": "[Rn]7s1",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      8,
      1
    ],
    "electronegativity": "0.7",
    "configSource": "PubChem"
  },
  {
    "number": 88,
    "symbol": "Ra",
    "name": "Radium",
    "period": 7,
    "group": 2,
    "row": 8,
    "column": 2,
    "mass": "226.02541",
    "category": "alkaline earth metal",
    "config": "[Rn]7s2",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      8,
      2
    ],
    "electronegativity": "0.9",
    "configSource": "PubChem"
  },
  {
    "number": 89,
    "symbol": "Ac",
    "name": "Actinium",
    "period": 7,
    "group": null,
    "row": 11,
    "column": 3,
    "mass": "227.02775",
    "category": "actinide",
    "config": "[Rn]7s2 6d1",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      9,
      2
    ],
    "electronegativity": "1.1",
    "configSource": "PubChem"
  },
  {
    "number": 90,
    "symbol": "Th",
    "name": "Thorium",
    "period": 7,
    "group": null,
    "row": 11,
    "column": 4,
    "mass": "232.038",
    "category": "actinide",
    "config": "[Rn]7s2 6d2",
    "shells": [
      2,
      8,
      18,
      32,
      18,
      10,
      2
    ],
    "electronegativity": "1.3",
    "configSource": "PubChem"
  },
  {
    "number": 91,
    "symbol": "Pa",
    "name": "Protactinium",
    "period": 7,
    "group": null,
    "row": 11,
    "column": 5,
    "mass": "231.03588",
    "category": "actinide",
    "config": "[Rn]7s2 5f2 6d1",
    "shells": [
      2,
      8,
      18,
      32,
      20,
      9,
      2
    ],
    "electronegativity": "1.5",
    "configSource": "PubChem"
  },
  {
    "number": 92,
    "symbol": "U",
    "name": "Uranium",
    "period": 7,
    "group": null,
    "row": 11,
    "column": 6,
    "mass": "238.0289",
    "category": "actinide",
    "config": "[Rn]7s2 5f3 6d1",
    "shells": [
      2,
      8,
      18,
      32,
      21,
      9,
      2
    ],
    "electronegativity": "1.38",
    "configSource": "PubChem"
  },
  {
    "number": 93,
    "symbol": "Np",
    "name": "Neptunium",
    "period": 7,
    "group": null,
    "row": 11,
    "column": 7,
    "mass": "237.048172",
    "category": "actinide",
    "config": "[Rn]7s2 5f4 6d1",
    "shells": [
      2,
      8,
      18,
      32,
      22,
      9,
      2
    ],
    "electronegativity": "1.36",
    "configSource": "PubChem"
  },
  {
    "number": 94,
    "symbol": "Pu",
    "name": "Plutonium",
    "period": 7,
    "group": null,
    "row": 11,
    "column": 8,
    "mass": "244.06420",
    "category": "actinide",
    "config": "[Rn]7s2 5f6",
    "shells": [
      2,
      8,
      18,
      32,
      24,
      8,
      2
    ],
    "electronegativity": "1.28",
    "configSource": "PubChem"
  },
  {
    "number": 95,
    "symbol": "Am",
    "name": "Americium",
    "period": 7,
    "group": null,
    "row": 11,
    "column": 9,
    "mass": "243.061380",
    "category": "actinide",
    "config": "[Rn]7s2 5f7",
    "shells": [
      2,
      8,
      18,
      32,
      25,
      8,
      2
    ],
    "electronegativity": "1.3",
    "configSource": "PubChem"
  },
  {
    "number": 96,
    "symbol": "Cm",
    "name": "Curium",
    "period": 7,
    "group": null,
    "row": 11,
    "column": 10,
    "mass": "247.07035",
    "category": "actinide",
    "config": "[Rn]7s2 5f7 6d1",
    "shells": [
      2,
      8,
      18,
      32,
      25,
      9,
      2
    ],
    "electronegativity": "1.3",
    "configSource": "PubChem"
  },
  {
    "number": 97,
    "symbol": "Bk",
    "name": "Berkelium",
    "period": 7,
    "group": null,
    "row": 11,
    "column": 11,
    "mass": "247.07031",
    "category": "actinide",
    "config": "[Rn]7s2 5f9",
    "shells": [
      2,
      8,
      18,
      32,
      27,
      8,
      2
    ],
    "electronegativity": "1.3",
    "configSource": "PubChem"
  },
  {
    "number": 98,
    "symbol": "Cf",
    "name": "Californium",
    "period": 7,
    "group": null,
    "row": 11,
    "column": 12,
    "mass": "251.07959",
    "category": "actinide",
    "config": "[Rn]7s2 5f10",
    "shells": [
      2,
      8,
      18,
      32,
      28,
      8,
      2
    ],
    "electronegativity": "1.3",
    "configSource": "PubChem"
  },
  {
    "number": 99,
    "symbol": "Es",
    "name": "Einsteinium",
    "period": 7,
    "group": null,
    "row": 11,
    "column": 13,
    "mass": "252.0830",
    "category": "actinide",
    "config": "[Rn]7s2 5f11",
    "shells": [
      2,
      8,
      18,
      32,
      29,
      8,
      2
    ],
    "electronegativity": "1.3",
    "configSource": "PubChem"
  },
  {
    "number": 100,
    "symbol": "Fm",
    "name": "Fermium",
    "period": 7,
    "group": null,
    "row": 11,
    "column": 14,
    "mass": "257.09511",
    "category": "actinide",
    "config": "[Rn] 5f12 7s2",
    "shells": [
      2,
      8,
      18,
      32,
      30,
      8,
      2
    ],
    "electronegativity": "1.3",
    "configSource": "PubChem"
  },
  {
    "number": 101,
    "symbol": "Md",
    "name": "Mendelevium",
    "period": 7,
    "group": null,
    "row": 11,
    "column": 15,
    "mass": "258.09843",
    "category": "actinide",
    "config": "[Rn]7s2 5f13",
    "shells": [
      2,
      8,
      18,
      32,
      31,
      8,
      2
    ],
    "electronegativity": "1.3",
    "configSource": "PubChem"
  },
  {
    "number": 102,
    "symbol": "No",
    "name": "Nobelium",
    "period": 7,
    "group": null,
    "row": 11,
    "column": 16,
    "mass": "259.10100",
    "category": "actinide",
    "config": "[Rn]7s2 5f14",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      8,
      2
    ],
    "electronegativity": "1.3",
    "configSource": "PubChem"
  },
  {
    "number": 103,
    "symbol": "Lr",
    "name": "Lawrencium",
    "period": 7,
    "group": null,
    "row": 11,
    "column": 17,
    "mass": "266.120",
    "category": "actinide",
    "config": "[Rn]5f14 7s2 7p1",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      8,
      3
    ],
    "electronegativity": "1.3",
    "configSource": "NIST"
  },
  {
    "number": 104,
    "symbol": "Rf",
    "name": "Rutherfordium",
    "period": 7,
    "group": 4,
    "row": 8,
    "column": 4,
    "mass": "267.122",
    "category": "transition metal",
    "config": "[Rn]7s2 5f14 6d2",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      10,
      2
    ],
    "electronegativity": null,
    "configSource": "PubChem"
  },
  {
    "number": 105,
    "symbol": "Db",
    "name": "Dubnium",
    "period": 7,
    "group": 5,
    "row": 8,
    "column": 5,
    "mass": "268.126",
    "category": "transition metal",
    "config": "[Rn]7s2 5f14 6d3",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      11,
      2
    ],
    "electronegativity": null,
    "configSource": "PubChem"
  },
  {
    "number": 106,
    "symbol": "Sg",
    "name": "Seaborgium",
    "period": 7,
    "group": 6,
    "row": 8,
    "column": 6,
    "mass": "269.128",
    "category": "transition metal",
    "config": "[Rn]7s2 5f14 6d4",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      12,
      2
    ],
    "electronegativity": null,
    "configSource": "PubChem"
  },
  {
    "number": 107,
    "symbol": "Bh",
    "name": "Bohrium",
    "period": 7,
    "group": 7,
    "row": 8,
    "column": 7,
    "mass": "270.133",
    "category": "transition metal",
    "config": "[Rn]7s2 5f14 6d5",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      13,
      2
    ],
    "electronegativity": null,
    "configSource": "PubChem"
  },
  {
    "number": 108,
    "symbol": "Hs",
    "name": "Hassium",
    "period": 7,
    "group": 8,
    "row": 8,
    "column": 8,
    "mass": "269.1336",
    "category": "transition metal",
    "config": "[Rn]7s2 5f14 6d6",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      14,
      2
    ],
    "electronegativity": null,
    "configSource": "PubChem"
  },
  {
    "number": 109,
    "symbol": "Mt",
    "name": "Meitnerium",
    "period": 7,
    "group": 9,
    "row": 8,
    "column": 9,
    "mass": "277.154",
    "category": "transition metal",
    "config": "[Rn]7s2 5f14 6d7 (calculated)",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      15,
      2
    ],
    "electronegativity": null,
    "configSource": "PubChem"
  },
  {
    "number": 110,
    "symbol": "Ds",
    "name": "Darmstadtium",
    "period": 7,
    "group": 10,
    "row": 8,
    "column": 10,
    "mass": "282.166",
    "category": "transition metal",
    "config": "[Rn]7s2 5f14 6d8 (predicted)",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      16,
      2
    ],
    "electronegativity": null,
    "configSource": "PubChem"
  },
  {
    "number": 111,
    "symbol": "Rg",
    "name": "Roentgenium",
    "period": 7,
    "group": 11,
    "row": 8,
    "column": 11,
    "mass": "282.169",
    "category": "transition metal",
    "config": "[Rn]7s2 5f14 6d9 (predicted)",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      17,
      2
    ],
    "electronegativity": null,
    "configSource": "PubChem"
  },
  {
    "number": 112,
    "symbol": "Cn",
    "name": "Copernicium",
    "period": 7,
    "group": 12,
    "row": 8,
    "column": 12,
    "mass": "286.179",
    "category": "transition metal",
    "config": "[Rn]7s2 5f14 6d10 (predicted)",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      18,
      2
    ],
    "electronegativity": null,
    "configSource": "PubChem"
  },
  {
    "number": 113,
    "symbol": "Nh",
    "name": "Nihonium",
    "period": 7,
    "group": 13,
    "row": 8,
    "column": 13,
    "mass": "286.182",
    "category": "post-transition metal",
    "config": "[Rn]5f14 6d10 7s2 7p1 (predicted)",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      18,
      3
    ],
    "electronegativity": null,
    "configSource": "PubChem"
  },
  {
    "number": 114,
    "symbol": "Fl",
    "name": "Flerovium",
    "period": 7,
    "group": 14,
    "row": 8,
    "column": 14,
    "mass": "290.192",
    "category": "post-transition metal",
    "config": "[Rn]7s2 7p2 5f14 6d10 (predicted)",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      18,
      4
    ],
    "electronegativity": null,
    "configSource": "PubChem"
  },
  {
    "number": 115,
    "symbol": "Mc",
    "name": "Moscovium",
    "period": 7,
    "group": 15,
    "row": 8,
    "column": 15,
    "mass": "290.196",
    "category": "post-transition metal",
    "config": "[Rn]7s2 7p3 5f14 6d10 (predicted)",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      18,
      5
    ],
    "electronegativity": null,
    "configSource": "PubChem"
  },
  {
    "number": 116,
    "symbol": "Lv",
    "name": "Livermorium",
    "period": 7,
    "group": 16,
    "row": 8,
    "column": 16,
    "mass": "293.205",
    "category": "post-transition metal",
    "config": "[Rn]7s2 7p4 5f14 6d10 (predicted)",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      18,
      6
    ],
    "electronegativity": null,
    "configSource": "PubChem"
  },
  {
    "number": 117,
    "symbol": "Ts",
    "name": "Tennessine",
    "period": 7,
    "group": 17,
    "row": 8,
    "column": 17,
    "mass": "294.211",
    "category": "halogen",
    "config": "[Rn]7s2 7p5 5f14 6d10 (predicted)",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      18,
      7
    ],
    "electronegativity": null,
    "configSource": "PubChem"
  },
  {
    "number": 118,
    "symbol": "Og",
    "name": "Oganesson",
    "period": 7,
    "group": 18,
    "row": 8,
    "column": 18,
    "mass": "295.216",
    "category": "noble gas",
    "config": "[Rn]7s2 7p6 5f14 6d10 (predicted)",
    "shells": [
      2,
      8,
      18,
      32,
      32,
      18,
      8
    ],
    "electronegativity": null,
    "configSource": "PubChem"
  }
];
